version: '3'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # This also copies over the ui folder into the backend container which isn't necessary. Noted
      # as an improvement to be made in the future.
      - .:/app
    environment:
      - DEBUG=True

  ui:
    container_name: ui
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "3000:3000"
